### ISSUE TITLE
import Template error

### ISSUE THREAD

**Issue by shaunglinux** [actiontech/actiontech_zabbix_mysql_monitor#8]
Created: Application "MySQL" on "Actiontech MySQL Server Template".
Created: Item "Total number of mysqld processes" on "Actiontech MySQL Server Template".
mb_strlen() expects parameter 1 to be string, array given [conf.import.php:130 → CConfigurationImport->import() → CConfigurationImport->processDiscoveryRules() → CAPIObject->create() → CAPIObject->__call() → czbxrpc::call() → czbxrpc::callAPI() → call_user_func() → CDiscoveryRule->create() → CDiscoveryRule->createReal() → DB::insert() → DB::checkValueTypes() → zbx_strlen() → mb_strlen() in /usr/share/zabbix/include/func.inc.php:955]
mysqli_real_escape_string() expects parameter 2 to be string, array given [conf.import.php:130 → CConfigurationImport->import() → CConfigurationImport->processDiscoveryRules() → CAPIObject->create() → CAPIObject->__call() → czbxrpc::call() → czbxrpc::callAPI() → call_user_func() → CDiscoveryRule->create() → CDiscoveryRule->createReal() → DB::insert() → DB::checkValueTypes() → zbx_dbstr() → mysqli_real_escape_string() in /usr/share/zabbix/include/db.inc.php:1224]
Array to string conversion [conf.import.php:130 → CConfigurationImport->import() → CConfigurationImport->processDiscoveryRules() → CAPIObject->create() → CAPIObject->__call() → czbxrpc::call() → czbxrpc::callAPI() → call_user_func() → CDiscoveryRule->create() → CDiscoveryRule->createReal() → DB::insert() → implode() in /usr/share/zabbix/include/classes/db/DB.php:450]
Error in query [INSERT INTO items (name,type,snmp_community,snmp_oid,delay,status,snmpv3_contextname,snmpv3_securityname,snmpv3_securitylevel,snmpv3_authprotocol,snmpv3_authpassphrase,snmpv3_privprotocol,snmpv3_privpassphrase,delay_flex,params,ipmi_sensor,authtype,username,password,publickey,privatekey,port,filter,lifetime,description,key_,trapper_hosts,hostid,flags,value_type,data_type,interfaceid,itemid) VALUES ('discovery mysql port','0','','','30','0','','','0','0','','0','','','','','0','','','','','',Array,'30','','MySQL.port_discovery','','10105','1','4','0',NULL,'23661')] [Unknown column 'Array' in 'field list']

**Comment by ikarishinjieva** [comment]
Could you provide more details, such as Zabbix version, UI snapshot, etc? Thanks.

**Comment by shaunglinux** [comment]
zabbix-server-2.2.6-1.el6.x86_64
mysql 5.6.13

**Comment by actiontech** [comment]
[actiontech_zabbix_agent_template_mysql_server.txt](https://github.com/actiontech/actiontech_zabbix_mysql_monitor/files/65169/actiontech_zabbix_agent_template_mysql_server.txt)

try the template please(remove screen because zabbix 2.2 do not support "graph prototype" in screen)
